[project]
name = "reggie-tools"
version = "0.1.0"
description = "Various databricks tools"
requires-python = ">=3.12"
dependencies = [
    # Databricks
    "databricks-sdk",
    "databricks-connect<=17.1",

    # Core computer vision + detection
    "ultralytics==8.2.92",
    "opencv-python==4.10.0.84",

    # Networking
    "requests",
    "urllib3",

]

[tool.setuptools.packages.find]
where = ["src"]

[tool.uv.pip]
find-links = ["./prpr/"]