[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "reggie-tools"
version = "0.1.0"
description = "Various databricks tools"
requires-python = ">=3.11,<=3.12.6"
dependencies = [
    # Databricks
    "databricks-sdk",
    "databricks-connect<=17.1",
    # Networking
    "requests",
    "urllib3",
    # Utils
    "filelock",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["reggie_tools*"]
