[project]
name = "reggie-tools"
version = "0.1.0"
description = "Various databricks tools"
requires-python = ">=3.12"
dependencies = [
    # Databricks
    "databricks-sdk",
    "databricks-connect<=17.1",
    # Networking
    "requests",
    "urllib3",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
