[versions]
kotlin = "2.1.20"
vaadin = "24.8.6"

[plugins]
vaadin = { id = "com.vaadin", version.ref = "vaadin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
vaadin-bom = { module = "com.vaadin:vaadin-bom", version.ref = "vaadin" }
databricks = { module = "com.databricks:databricks-sdk-java", version = "0.59.0" }
