[build-system]
requires = [
    "uv_build>=0.8.23,<0.9.0",
]
build-backend = "uv_build"

[project]
name = "reggie-rx"
version = "0.0.1+ga44c934"
requires-python = ">=3.12"
dependencies = [
    "reactivex",
]
