[build-system]
requires = [
    "uv_build>=0.8.23,<0.9.0",
]
build-backend = "uv_build"

[project]
name = "reggie-core"
version = "0.0.1+gdce2016"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
